In [1]:
#importing the libraries 
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
#checking the pandas version
pd.__version__

'1.5.3'

In [9]:
#install wget
pip install wget

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for wget: filename=wget-3.2-py3-none-any.whl size=9680 sha256=5893d2776216a0256eb676c5f85023aa48c945c2bb2c8c00f0f3e0fa9501f604
  Stored in directory: c:\users\phikolomzi samka\appdata\local\pip\cache\wheels\40\b3\0f\a40dbd1c6861731779f62cc4babcb234387e11d697df70ee97
Successfully built wget
Note: you may need to restart the kernel to use updated packages.


In [72]:
import wget

url = "https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv"
wget.download(url)


100% [..........................................................................] 1423529 / 1423529

'housing (1).csv'

In [75]:
df = pd.read_csv('housing.csv')
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [77]:
#unique values the ocean_proximity column have
len(np.unique(df['ocean_proximity']))

5

In [78]:
np.unique(df['ocean_proximity'])

array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
      dtype=object)

In [79]:
#the average value of the median_house_value for the houses located near the bay
df[df['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean()

259212.31179039303

In [80]:
#calculating the average of total_bedrooms column in the dataset
df['total_bedrooms'].mean()

537.8705525375618

In [81]:
#filling nan values with the mean and saving them
df = df.fillna(df['total_bedrooms'].mean())

In [82]:
#checking if the mean changed after filling
df['total_bedrooms'].mean()

537.8705525375617

In [83]:
#Selecting options located in islands along their corresponding housing_median_age, total_rooms, total_bedrooms and transform it in a numpy array

X = df[df['ocean_proximity'] == 'ISLAND'][['housing_median_age', 'total_rooms', 'total_bedrooms']].to_numpy()
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [86]:
# matrix multiplication between X.T (transpose) and X
XTX = np.dot(X.T, X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [87]:
#The inverse of the transpose

inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [94]:
#creating a numpy array

y = np.array([950, 1300, 800, 1000, 1300])

In [100]:
#multpiplying the inverse of X and transpose of X, X.T

z = np.dot(inv_XTX, X.T)

In [101]:
#getting the last elemnt of w
w = np.dot(z , y)
w[-1]

5.6992294550655656